---
title: "Covid-19: Lockdown Decision in Switzerland"
subtitle: "Subjective Expected Utility"
author: "Jerom Kämpfer, Robin Scherrer and Nicolas Schuler"
date: "January 15th, 2020"
output: 
  pdf_document:
    number_sections: true

fontsize: 11pt
urlcolor: blue
    
---
> Far-reaching measures were decided by the Swiss federal council to counter the Covid-19 pandemic. This paper analyses this decision using separate models of the health and economic impact with the Subjective Expected Utility Theory (SEU). Based on different assumptions regarding the impact of the pandemic, a partial lockdown would have been suggested. In order to assess the uncertainty about the specifications, a [shiny application](https://nschuler.shinyapps.io/SEU_Covid_V4/) has been set up. Despite considering different aspects, different types of uncertainty remain and therefore make it unpossible to give a clear suggestion.

# Motivation
Due to the Covid-19 pandemic, the Swiss federal council made a decision on March 16th, 2020 with a massive impact on society, economy and healthcare. Shops, schools, theaters, museums, restaurants, bars, libraries and many more institutions were closed, large events with more than 100 people were forbidden and the Swiss armed forces were mobilized for the first time since world war two (cf [press conference](https://www.youtube.com/watch?v=fnuTzODXLvw)).

Within this project, this decision shall be analyzed and assessed using Subjective Expected Utility Theory (SEU). 

# Subjective Expected Utility
SEU was introduced by Leonard Savage in 1954[^1] and gives the possibility to assess decisions under uncertainty in the absence of physical probabilities.

Following components must be defined to apply SEU for our purpose:

* Acts $a\in A$: decision opportunities;
* States $i$: mutually exclusive and exhaustive events;
* Consequences $x_{ia}$: the outcome for every act $a\in A$ and state $i$ (i.e. the outcome if $a$ is decided and $i$ occurs);
* Subjective Prior $\tilde{p}_i$: the subjective belief on the likelihood of $i$ occuring;
* Utility function $u(x_{ia})$: the utility function for every consequence, complying with the SEU-postulates.

Based on the SEU, a decision maker should choose the act $a$, which has the highest expected utility of all acts $a\in A$. In mathematical notation, the decision criteria can be represented as:
$$\max_a \sum_{\forall i} x_{ia}*\tilde{p}_i$$

[^1]: Savage, L.J. (1954) “The Foundations of Statistics” *New York, Wiley*.

# Our modelling Approach
Following the suggestion of Berger et al. (2020, p.5)[^2], this assessment will be made based on separate modellings of the health and disease impact and the economic impact. Subsequently these inputs will be used in the formal decision rule, the SEU.

There are countless possibilities regarding measures that the federal council could have decided. Assuming that it would have been unfeasible to take minor measures than the ones already implemented earlier, we only consider the following two acts:

* Partial Lockdown: Minor restrictions, e.g. on large events, restaurants, bars;
* Full Lockdown: Major restritions, e.g. closure of shops, schools, universities and the granting of loans and subventions for the economy.

Furthermore, only the 33 days following the date of decision will be considered.

[^2]: Berger, L. et al. (2020) "Uncertainty and decision-making during a crisis: How to make policy decisions in the COVID-19 context?" *Chicago, Macro Finance Research Program*.

## Economic Model


## Health Model
The health costs are the first cost driver in our model. We chose to consider only the costs incurred due to the years of life lost because of corona deaths. For example, one could have also considered the costs of mental illness because of the consequences of a full lockdown. Still, the data situation was scarce when the decision had to be made to declare a full lockdown or keep a partial lockdown. We took six factors into account to calculate the health costs.
$$L_{tij}^a=(Infected_{t-TrmT}\times R_{0_i}^a)\times FatR_j \times LYrs \times CpLYL$$
with $a \in$ {Partial Lockdown = PL, Full Lockdown = FL}\
and $i \in$ {low, medium, high}, $j \in$ {low, medium, high}

$TrmT$: Transmitting Time\
$CpLYL$: Cost per Year of Life\
$R_0$: Reproduction Rate\
$\downarrow R_0$: Lockdown Discount on $R_0$\
$FatR$: Fatality Rate\
$LYrs$: Lost Years

### Transmitting Time
The coronavirus's incubation period showed a large variance across many of the studies available at that time. We assumed that an infected person infects $R_0$ people as soon as symptoms occur, namely after the incubation period. As some people probably do not spread the disease immediately on the first day of the appearance of symptoms, we used in our calculations the transmitting time instead of the incubation period. According to a study of [Eurosurveillance](https://www.eurosurveillance.org/content/10.2807/1560-7917.ES.2020.25.5.2000062;jsessionid=ssKL_IfM1Au524K1jqmhqJRU.i-0b3d9850f4681504f-ecdclive) the 50th percentile of the incubation period is 6.4 days, and the 97.5th percentile is 11.1 days. To get the transmitting time, we calculated the mean of the percentiles and rounded the result. We arrived at a transmitting time of nine days.
$$TrmT = \frac{IncP_{50th\text{ }PCTL}+IncP_{97.5th\text{ }PCTL}}{2}\approx 9\text{ days}$$

### Cost per Year of Life
The cost per year of life represents the monetary loss of one year of life lost due to a corona death. We implicitly assumed that the value of life is not infinite. Another assumption we made is that each year of life has the same value regardless of the dead person's age. We came across a case from the [Federal Court](https://www.bger.ch/ext/eurospider/live/de/php/aza/http/index.php?highlight_docid=aza%3A%2F%2F23-11-2010-9C_334-2010&lang=de&type=show_document&zoom=YES&) where the maximum amount of CHF 100,000 was considered appropriate for a year of life saved.
$$CpLYL=100'000 \text{ CHF}$$

### Reproduction Rate and Lockdown Discount
The reproduction rate indicates how many people an infected person passes on the virus after the transmitting time. Since the data on the reproduction rate was very scarce at the time of the decision on a lockdown, we distinguished between three different scenarios (low, medium, high) in our calculations. We then subtracted the lockdown discount (in per cent) from each scenario in the full lockdown scenario. To obtain the values for the different scenarios, we used a study from the [Journal of Travel Medicine](https://academic.oup.com/jtm/article/27/2/taaa021/5735319), which analysed twelve individual studies from China and took the smallest value, the arithmetic mean and the largest value. For the lockdown discount, we used a study by the [World Health Organization](https://www.who.int/bulletin/volumes/98/7/20-254045/en/). We assumed that all three scenarios have the same probability and the World Health Organization was communicating with the government of Switzerland before publishing the results.

|                        |   low       |   medium    |     high       |
|:-----------------------|------------:|------------:|---------------:|
|Partial Lockdown        |   1.4       |   2.79      |     3.3        |
|Full Lockdown ($-55\%$) |   0.63      |   1.26      |     1.49       |

\pagebreak
### Fatality Rate
The fatality rate indicates the proportion of infected persons who die from the coronavirus. Here, too, the data was very scarce at the time in question. We again distinguished between three scenarios (low, medium, high) for which we assumed the same probability. Since a lockdown does not change the virus's lethality, we have not distinguished between a partial lockdown and full lockdown. We obtained the data for the average mortality rate from [China CDC Weekly](https://globalhandwashing.org/wp-content/uploads/2020/03/COVID-19.pdf) and [Annals of Translational Medicine](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7049028/).

|         |low|medium|high|
|:-----------------------|------------:|------------:|---------------:|
|Partial Lockdown        |   0.15%       |   2.3%      |     5.25%        |
|Full Lockdown |   0.15%       |   2.3%      |     5.25%        |

We then extrapolated the average mortality rates above down to age groups based on an age distribution from [China CDC Weekly](https://globalhandwashing.org/wp-content/uploads/2020/03/COVID-19.pdf). We have implicitly assumed that the fatality rates of the individual age groups in Switzerland are the same as in China.

### Lost Years
To calculate the number of years of life lost by a covid deceased, we used data from Switzerland's [Federal Statistical Office](https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/geburten-todesfaelle/lebenserwartung.html). For each year of life up to 99, the number of years of life still expected was listed. Since life expectancy differs between males and females, and the distribution of sexes was almost identical before the lockdown decision regarding to another page of the [Federal Statistical Office](https://www.covid19.admin.ch/de/overview), we used the average life expectancy per age group in our calculations.

|         |0-9|10-19|20-29|30-39|40-49|50-59|60-69|70-79|80+|
|:----------------|------------:|------------:|---------------:|------------:|------------:|------------:|------------:|------------:|------------:|
|Life Expectancy     |   77.4   | 67.4  |   57     | 47.1 |37.4   | 28.1  |   19.4     | 11.8 | 5.9

## Utility Function
Regarding the utility function it is assumend, that the decision maker's utility only depends on health cost and economic cost. Furthermore it is assumed, that the utility decreases in both. It is also assumed, that the decision maker is risk neutral.

A straightforward representation of these preferences is the following:
$$u_{neutral}(EconCost, HealthCost)= -\frac{EconCost+HealthCost}{10^9}$$
Beside its simplicity, its interpretability is also an advantage. The resulting value can be perceived as monetary loss equivalent of health and economic cost (in Bn CHF). Note: its values are likely to be negative.

# Results and Discussion
Based on all mentioned assumptions, following subjective expected utilities are obtained for the two acts:

|partial lockdown|full lockdown|
|---------------:|------------:|
|   **-8.587**   |   -9.648    |

When following Savage's approach with the SEU, based on the mentioned assumptions, the Swiss federal council should have decided a partial lockdown. But as the values already suggest, the assumptions made lead to a very close decision.

In order to assess the model's sensitivity to critical input parameters easily, our results are deployed in this [shiny application](https://nschuler.shinyapps.io/SEU_Covid_V4/). As can be seen in the following table, different ceteris paribus changes in the assumptions, which might also have been plausible in March 2020, change the suggested decision:

|Variable         |assumed value|changed value|partial lockdown|full lockdown|
|:----------------|------------:|------------:|---------------:|------------:|
|Risk-profile     |   neutral   | averse[^3]  |   -135.122     | **-93.537** |
|Cost LYOL        |   100'000   |   120'000   |     -9.876     |  **-9.768** |
|Ld duration      |        33   |        35   |    -11.032     |  **-9.937** |
|Credit default   |         5%  |       1.8%  |     -8.587     |  **-8.390** |
|Transmission Time|         9   |         8   |    -12.164     |  **-9.775** |
|$R_0$ pessimistic|       3.3   |       3.6   |     -9.943     |  **-9.739** |

[^3]: For the risk-averse profile, following utility function was assumed:
$u_{averse}(EC, HC)= -(\frac{EconCost+HealthCost}{10^9})^2$

Berger et al. (2020)[^4] describe three types of uncertainty, which are relevant for models in the context of the Covid-19 crisis.

[^4]: Berger, L. et al. (2020) "Uncertainty and decision-making during a crisis: How to make policy decisions in the COVID-19 context?" *Chicago, Macro Finance Research Program*.

First, uncertainty within the model, referring to the standard notion of risk, meaning the uncertainty of outcomes with prespecified probabilities. In our case, this uncertainty goes even beyond this, since the probabilities of the occurence of the states is unknown and, based on de Finetti's principle of unsufficient reason, is assumed to be equal for all states.

Second, uncertainty across models, which reflects the uncertainty about parameters for the models. This issue can be seen in the table above, showing that slight changes in the assumptions can lead to a different optimal decision.

Third, uncertainty about models, referring to the property of a model, that it is a simplification of a more complex phenomenon and therefore is misspecified to some extent. Although our models reflect many aspects of the impact of the Covid-19 crisis, there are certainly some issues missing. Neither the impact on mental health, nor the capacities of the health care system were explicitly specified in the models, leading to a bias.

Due to many remaining uncertainties regarding the models, it is not possible to come to very clear result based on these models.


# Appendix



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

